version: '3'

services:
  db:
    container_name: mycreativefinancing-db
    image: mysql
    networks:
      - mycreativefinancing_network
    restart: on-failure
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - mycreativefinancing-datavolume:/var/lib/mysql
  api:
    container_name: mycreativefinancing-api
    build: .
    networks:
      - mycreativefinancing_network
    env_file:
      - .env
    restart: on-failure
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
    depends_on:
      - db
    entrypoint: ["/app/wait-for-it.sh", "db:3306", "--", "./main"]
networks:
  mycreativefinancing_network:
    driver: bridge
volumes:
  mycreativefinancing-datavolume: